### ISSUE TITLE
Drag elasticity

### ISSUE THREAD

**Issue by anthonycastelli** [spaceelephant/SESlideTableViewCell#11]
Is there any way to give the drag effect more resistance once the buttons are shown? A good example of what I am talking about is if you swipe to delete on a message in the Messages.app, the cell will still slide but becomes hard to pull. Instagram comment's also do this.

**Comment by spaceelephant** [comment]
I've just added a feature to add resistance once the buttons are shown completely.
```swift
cell.slideElasticity = .Hard
```
This feature can be used with 0.7.0 or later.
Please check the latest version.

**Comment by anthonycastelli** [comment]
`.Hard` is closer to what i'm trying to achieve, but any chance an `.ExtraHard` option could be added? I could look into how you did it and submit a PR if need be.

**Comment by spaceelephant** [comment]
Yes. Pull Request is always welcome!

**Comment by anthonycastelli** [comment]
Alright, will dig into this Monday :)

**Comment by spaceelephant** [comment]
@anthonycastelli 
I've closed this issue.
Please send Pull Request if you have one.
