### ISSUE TITLE
Compile error for missing memory management qualifiers

### ISSUE THREAD

**Issue by laeroah** [spaceelephant/SESlideTableViewCell#15]
pull request made: https://github.com/spaceelephant/SESlideTableViewCell/pull/14

<img width="374" alt="screen shot 2016-10-25 at 2 22 16 pm" src="https://cloud.githubusercontent.com/assets/1928509/19698798/b91cfda4-9abe-11e6-8331-d337e1d03f36.png">

Thank you!

**Comment by spaceelephant** [comment]
Thank you for your PR.
I've just merged it.
