### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by ivangodfather** [spaceelephant/SESlideTableViewCell#4]
I want to update the content of the cell while is showed. 
"Limitations
The animation of the contents in the cell stops while buttons are displayed. This comes from using snapshot to display the existing content in the cell."

What alternative i have? I have a plus button to increment a  a number inside a label, and its weird when you add units the label doesnt get udpated...

**Comment by spaceelephant** [comment]
There is no way to update your content while buttons are shown.
I'll figure out the way to update the snapshot view manually.

**Comment by spaceelephant** [comment]
I added a feature to update the snapshot of the content view of the cell.
```objc
- (void)updateContentViewSnapshot;
```
Please call this function after updating your content.

**Comment by spaceelephant** [comment]
This issue has been fixed with 0.3.0.
