### ISSUE TITLE
One row at a time

### ISSUE THREAD

**Issue by fbara** [spaceelephant/SESlideTableViewCell#5]
I would like to have only 1 set of row buttons visible at a time.  If the user slides a cell and exposes the buttons, but doesn't tap the buttons, and then slides a different cell, can the original cell 'close'?  I'm looking over your code but I can't find a place for me to make this type of change.

Thanks!

**Comment by spaceelephant** [comment]
To implement a feature you mentioned above, I think it is better to use SESlideTableViewCellDelegate.
The cell itself does not know other cells in the TableView, so a delegate class should handle it.

I've just added some features to SESlideTableViewCellDelegate with version 0.4.0 to know several events.

- slideTableViewCell:willSlideToState:
- slideTableViewCell:DidSlideToState:
- slideTableViewCell:willShowButtonsOfSide:

You can call setSlideToState:animated: in these function to hide buttons which are currently displayed.

```objc
- (void)slideTableViewCell:(SESlideTableViewCell *)cell willSlideToState:(SESlideTableViewCellSlideState)slideState {
    NSIndexPath* indexPath = [self.tableView indexPathForCell:cell];
    if (indexPath) {
        if (slideState != SESlideTableViewCellSlideStateCenter) {
            if (m_currentIndexPath) {
                SESlideTableViewCell* cell = [self.tableView cellForIndexPath:m_currentIndexPath];
                [cell setSlideState:SESlideTableViewCellSlideStateCenter animated:YES];
            }
        }
    }
}

- (void)slideTableViewCell:(SESlideTableViewCell *)cell didSlideToState:(SESlideTableViewCellSlideState)slideState {
    NSIndexPath* indexPath = [self.tableView indexPathForCell:cell];
    if (slideState != SESlideTableViewCellSlideStateCenter) {
        m_currentIndexPath = indexPath;
    }
}

```

**Comment by fbara** [comment]
That works perfectly!  Thanks for looking into this so quickly.

**Comment by sai-prasanna** [comment]
@spaceelephant  There is still a issue in this method where I can use 2 fingers and slide 2 cells at the same time .. I

**Comment by spaceelephant** [comment]
Thank you @sai-prasanna 
I altered the implementation.
I hope this might be helpful.
```
- (void)slideTableViewCell:(SESlideTableViewCell *)cell willSlideToState:(SESlideTableViewCellSlideState)slideState {
    NSIndexPath* indexPath = [self.tableView indexPathForCell:cell];
    if (indexPath) {
        if (slideState != SESlideTableViewCellSlideStateCenter) {
            if (m_currentIndexPath) {
                SESlideTableViewCell* cell = [self.tableView cellForIndexPath:m_currentIndexPath];
                [cell setSlideState:SESlideTableViewCellSlideStateCenter animated:YES];
            }
        }
        m_currentIndexPath = indexPath;
    }
}
```

**Comment by sai-prasanna** [comment]
That works :+1:  Thanks.. I implemented a bit differently in swift, but same logic.

Can you explain how this actually works ? Little confused

    func slideTableViewCell(cell: SESlideTableViewCell!, willSlideToState slideState:     SESlideTableViewCellSlideState) {
            let indexPath = myView.tableView.indexPathForCell(cell)
            if let _ = indexPath {
                if (slideState != .Center) {
                    slidedCell?.setSlideState(.Center, animated: true)
                }
                slidedCell = cell
            }
        }

**Comment by spaceelephant** [comment]
I think this could be better.
```
        let indexPath = myView.tableView.indexPathForCell(cell)
        if let _ = indexPath {
            if (slideState != .Center) {
                slidedCell?.setSlideState(.Center, animated: true)
                slidedCell = cell
            }
        }
```
When a cell will slide to left or right (not center), close the previously slid cell and set a new cell as slid cell.
Even when multiple cells are slid, ```willSlideToState:``` method is called once for each cell, so only the last one is open and the others are closed.

**Comment by sai-prasanna** [comment]
>Even when multiple cells are slid, willSlideToState: method is called once for each cell, so only the last >one is open and the others are closed.

Oh now I get it, I was using old copy of SES before , which hand only canSlideToState which got fired many times for the cells.., So I t couldn't get it to work
