### ISSUE TITLE
Close cell when another is opened

### ISSUE THREAD

**Issue by fbara** [spaceelephant/SESlideTableViewCell#6]
I would like any open cell/row to close when the user 1) opens a new cell, and 2) scrolls the tableview, and 3) whenever the user taps on one of the cell buttons.  Basically, I'm looking for a way to force-close a cell.

Is there a way to perform these actions with the SESlideTableViewCell delegates?

**Comment by spaceelephant** [comment]
1) open a new cell
You can know when a cell is opened with SESlideTableViewCellDelegate:
```objc
- (void)slideTableViewCell:(SESlideTableViewCell*)cell willSlideToState:(SESlideTableViewCellSlideState)slideState
```
or
```objc
- (void)slideTableViewCell:(SESlideTableViewCell *)cell wilShowButtonsOfSide:(SESlideTableViewCellSide)side;
```
The former is called when the user release his/her finger off the screen.
The latter is called when a button of the cell begins to be displayed.

2) scroll the TableView
You can know when a table view scrolls with UIScrollViewDelegate:
```objc
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView;
```

3) the user taps on one of the cell buttons
You can know when a cell's button is pushed with SESlideTableViewCellDelegate:
```objc
- (void)slideTableViewCell:(SESlideTableViewCell*)cell didTriggerLeftButton:(NSInteger)buttonIndex;
- (void)slideTableViewCell:(SESlideTableViewCell*)cell didTriggerRightButton:(NSInteger)buttonIndex;

```

**Comment by fbara** [comment]
Thanks, again, @spaceelephant.  What do I call to close a cell that's open?  I only want the user to have 1 open cell at a time plus, when they tap a button I want to close any open cell.

**Comment by spaceelephant** [comment]
You can close a cell with
```objc
[cell setSlideState:SESlideTableViewCellSlideStateCenter animated:YES];
```

So, remember a opened cell and call this method for it when a user tap a button.

**Comment by fbara** [comment]
I did that and it wasn't working.  It must be something I'm doing wrong.  I'll work on it a bit and get back to you.  I appreciate your help on all this.

**Comment by fbara** [comment]
I found the problem.  I had `rowCanSlide` still marked as `FALSE`.  Once I changed that to the correct value, the row slid back as expected.  Thanks again for helping!
